name: Patch Obsidian with revanced Molten glass

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-and-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest Obsidian release
        id: latest_release
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest | jq -r '.name')
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          echo "Latest release: $LATEST_VERSION"

      - name: Check if already patched
        id: check_version
        run: |
          if [ -f latest_version.txt ] && grep -q "$LATEST_VERSION" latest_version.txt; then
            echo "Latest version already processed, skipping."
            exit 0
          else
            echo "LATEST_VERSION=$LATEST_VERSION" > latest_version.txt 
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add latest_version.txt
            git commit -m "Update latest version to ${{ env.LATEST_VERSION }}"
            git push
          fi

      - name: Download APK
        run: |
          APK_URL="https://github.com/obsidianmd/obsidian-releases/releases/download/v$LATEST_VERSION/obsidian-$LATEST_VERSION.apk"
          curl -L $APK_URL -o obsidian-$LATEST_VERSION.apk

      - name: Setup ReVanced CLI
        run: |
          wget https://github.com/ReVanced/revanced-cli/releases/download/v5.0.0/revanced-cli-5.0.0-all.jar -O revanced-cli.jar
          wget https://github.com/Faith001/revanced-molten-glass/releases/download/mg-1.0.0/patches-mg-1.0.0.rvp

      - name: Patch APK
        run: |
          java -jar revanced-cli.jar patch -p patches-mg-1.0.0.rvp obsidian-$LATEST_VERSION.apk

      - name: Save version
        run: echo "$LATEST_VERSION" > latest_version.txt

      - name: Upload patched APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: patched-obsidian
          path: obsidian-${{env.LATEST_VERSION}}-patched.apk

      - name: Create GitHub Release and Upload APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$LATEST_VERSION" obsidian-$LATEST_VERSION-patched.apk \
            --title "Obsidian ReVanced Molten $LATEST_VERSION" \
            --notes "This is an automatically patched version of Obsidian using ReVanced Molten patch."
